### ISSUE TITLE
`customVolume` is not working 

### ISSUE THREAD

**Issue by huseyinbabal** [hazelcast/charts#138]
**With Helm 2;**

`customVolume` was working until [this commit](https://github.com/hazelcast/charts/commit/dec16bdecf67a282b8de4c6ef15586dc08c99b1d) and stopped working with [this commit](https://github.com/hazelcast/charts/commit/48cf211b74740d893421bb7a76cec9d7bba8aad1). You can simply verify it by;

```
helm upgrade --install my-chart \
--set hazelcast.licenseKey=<key> \
--set customVolume.hostPath.path=/tmp/  \
hazelcast/hazelcast-enterprise --version 3.4.4 --debug --dry-run
```
It will throw `Error: YAML parse error on hazelcast-enterprise/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 101: mapping values are not allowed in this context`. Here line 101 is not 101th line in yaml file, it is relative line number in dry run output which is equal to 

```
volumes:
- name: hazelcast-storage
    configMap:
    name: huseyin-hz-hazelcast-enterprise-configuration
- name: hazelcast-custom
            hostPath:
    path: /tmp/
```
