### ISSUE TITLE
Use Role instead of ClusterRole

### ISSUE THREAD

**Issue by martonsz** [hazelcast/charts#159]
Is it possible to not use a cluster wide RBAC configuration?
If it is possible. Can it be a option in the `values.yaml`?

I am using a hosted kubernetes where I don't have permission to create cluster-wide Roles limited to two namespaces.

I have successfully installed the [Hazelcast](https://github.com/hazelcast/charts/tree/master/stable/hazelcast) chart by modifying the generated `role.yaml` and `rolebinding.yaml`. And it seems to work OK. But I am not an expert on RBAC or Hazelcast.

The following modified `role.yaml` and `rolebinding.yaml` worked for me.

```yaml
---
# Source: hazelcast/templates/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: hazelcast-production
  labels:
    app.kubernetes.io/name: hazelcast
    helm.sh/chart: hazelcast-3.4.9
    app.kubernetes.io/instance: "hazelcast"
    app.kubernetes.io/managed-by: "Helm"
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods
  - nodes
  verbs:
  - get
  - list
  
---
# Source: hazelcast/templates/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: hazelcast-production
  labels:
    app.kubernetes.io/name: hazelcast
    helm.sh/chart: hazelcast-3.4.9
    app.kubernetes.io/instance: "hazelcast"
    app.kubernetes.io/managed-by: "Helm"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: hazelcast-production
subjects:
- kind: ServiceAccount
  name: hazelcast
  namespace: production


```

## Other info

```
Chart: hazelcast/hazelcast 3.4.9

helm version
version.BuildInfo{Version:"v3.3.1", GitCommit:"249e5215cde0c3fa72e27eb7a30e8d55c9696144", GitTreeState:"clean", GoVersion:"go1.14.7"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.8", GitCommit:"9f2892aab98fe339f3bd70e3c470144299398ace", GitTreeState:"clean", BuildDate:"2020-08-13T16:12:48Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.6", GitCommit:"7015f71e75f670eb9e7ebd4b5749639d42e20079", GitTreeState:"clean", BuildDate:"2019-11-13T11:11:50Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by leszko** [comment]
One option to solve such issues is to set `rbac.create` to `false` and use [Hazelcast Kubernetes: DNS Lookup]([url](https://github.com/hazelcast/hazelcast-kubernetes#dns-lookup))

Saying that I'm fine to add an option to create Role instead of `ClusterRole` for the scenarios you mention. You can contribute a PR if you want. I'd see it something like `rbac.clusterRole` with the default to `true`.

**Comment by martonsz** [comment]
I have tried setting `rbac.create: false` and used the DNS lookup. But then I get the following problem https://github.com/hazelcast/hazelcast/issues/17062. Which seems to be fixed in a coming version https://github.com/hazelcast/hazelcast/pull/17239.



I have now been told by my kubernetes provider that `nodes` is a cluster-wide resource. That is why it needs to be a `ClusterRole` instead of a `Role`. 

So my question is now. Is the `nodes` resource really needed by Hazelcast? Or can I use a `Role` where I skip the `nodes` part?

```yaml
...
resources:
  - endpoints
  - pods
  #- nodes
  verbs:
  - get
  - list
 ...
```

**Comment by martonsz** [comment]
My workaround for now is to use `rbac.create: false` and create a new `Service` (that is not headless) that the clients can use. 
Now my clients can automatically reconnect if the hazelcast server changes IP.

```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-headed
  labels:
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hazelcast
    app.kubernetes.io/instance: "hazelcast"
    role: hazelcast
  ports:
  - protocol: TCP
    port: 5701
    targetPort: hazelcast
    name: hzport
```
