### ISSUE TITLE
Make service port name customizable in the Helm chart for better Rancher compatibility

### ISSUE THREAD

**Issue by maurizio-lattuada** [hazelcast/charts#165]
I'm using Hazelcast as Tomcat session manager for some web applications deployed in a Kubernetes cluster managed by Rancher. I'm using the chart version 3.4.1.

In Rancher it is possible to have integrated Prometheus monitoring by adding some annotations to the Deployment, e.g.
```yaml
        prometheus.io/scrape: 'true'
        prometheus.io/port: '8088'
        prometheus.io/path: "/metrics"
        field.cattle.io/workloadMetrics: '[{"path":"/metrics","port":8088,"schema":"HTTP"}]'
```
so, with some _black magic_, the internal Rancher monitoring is able to scrape these metrics.

As far as I observed, that _black magic_ mentioned above involves the creation under the hood of a new Service by Rancher having the port 8088 called `metrics<portNumber>`, e.g. `metrics8088`.

With this Helm chart, if we enable the metrics like:
```yaml
metrics:
  enabled: true
  service:
    port: 8088
```
when deploying this chart, a new service is correctly created exposing the port 8088 with name `metrics`.
Unfortunately, here Rancher finds this service already exposing port 8088, so it does not create _its own_ service having port 8088 called `metrics8088`, thus these metrics cannot be scraped correctly by the Rancher internal monitoring.

Would be nice to have the port name of the metrics Service as parameter for the Helm chart as well, and leave of course `metrics` as default value if not provided, e.g.:
```yaml
metrics:
  enabled: true
  service:
    port: 8088
    portName: metrics8088
```

Now as a workaround I had to delete the metrics Service created when deploying Hazelcast and let Rancher kicking in to create its own service with port 8088 exposed with name `metrics8088`.

Thank you
