### ISSUE TITLE
Write how to setup dns discovery in Readme file

### ISSUE THREAD

**Issue by andrey-gava** [hazelcast/charts#186]
Hello!

Despite fixed bug mentioned in #58 I still cant figure out how to make it work. 
I tried to install last available chart version 3.5.4 with all default values except that I edited provided values.yaml
and set it like this
```
     kubernetes:
            enabled: true
            service-name: 
            service-dns: ${serviceName}
            namespace: ${namespace}
```
but hazelcast  pods trow the same error in logs:
`Exception in thread "main" com.hazelcast.config.InvalidConfigurationException: The configuration entry under hazelcast/network/join/kubernetes/service-name is null. Please check if the provided YAML configuration is well-indented and no blocks started without sub-nodes.`
And no mater how I try to configure it, with 'null' value or even without 'service-name: ' string it still errors in logs. 
Maybe I do it in wrong way?
And by the way when used with dns discovery mode do I set only `rbac.create=false` or full list like this:
```
rbac.create=false
serviceAccount.create=false
serviceAccount.automountToken=false
```
Cant someone put description on this to Readme file @leszko ?

**Comment by leszko** [comment]
I update README in #187 

Btw. here's the configuration you need:
```
hazelcast:
  yaml:
    hazelcast:
      network:
        join:
          kubernetes:
            service-dns: "${serviceName}.${namespace}.svc.cluster.local"
            service-name: ''
            namespace: ''
rbac:
  create: false
```
