### ISSUE TITLE
Question: ConfigMap Hazelcast configuration file(s) for v4.1.1

### ISSUE THREAD

**Issue by jisnardo** [hazelcast/charts#192]
Hi, I'm using this two hazelcast helm charts:

```
[jisnardo@edxyz ~]$ helm3 search repo hazelcast -l
NAME                              CHART VERSION APP VERSION DESCRIPTION
hazelcast/hazelcast               2.10.3        3.12.9      Hazelcast IMDG is the most widely used in-memor...
hazelcast/hazelcast               3.5.6         4.1.1       Hazelcast IMDG is the most widely used in-memor...
```

Inside the values I have this:

```
NAME                              CHART VERSION APP VERSION DESCRIPTION
hazelcast/hazelcast               2.10.3        3.12.9      Hazelcast IMDG is the most widely used in-memor...
```

```
# Hazelcast properties
hazelcast:
...
  # existingConfigMap defines a ConfigMap which contains Hazelcast configuration file(s) that are used instead hazelcast.yaml configuration below
  # existingConfigMap:
  # yaml is the Hazelcast YAML configuration file
  yaml:
    hazelcast:
      cluster:
        name: MYAPP
      instance:
        name: hz3MYAPP
      group:
        name: hz3MYAPP
        password: 123456abcDEFG
      network:
        join:
          multicast:
            enabled: false
          kubernetes:
            enabled: true
            service-name: ${serviceName}
            namespace: ${namespace}
            resolve-not-ready-addresses: true
        rest-api:
          enabled: true
          endpoint-groups:
            HEALTH_CHECK:
              enabled: true
      management-center:
        enabled: ${hazelcast.mancenter.enabled}
        url: ${hazelcast.mancenter.url}
```

```
NAME                              CHART VERSION APP VERSION DESCRIPTION
hazelcast/hazelcast               3.5.6        4.1.1      Hazelcast IMDG is the most widely used in-memor...
```

```
# Hazelcast properties
hazelcast:
...
# existingConfigMap defines a ConfigMap which contains Hazelcast configuration file(s) that are used instead of hazelcast.yaml configuration below
# existingConfigMap:
# yaml is the Hazelcast YAML configuration file
yaml:
hazelcast:
  cluster:
    name: MYAPP
  instance:
    name: hz4MYAPP
  group:
    name: hz4MYAPP
    password: 123456abcDEFG
  network:
    join:
      multicast:
        enabled: false
      kubernetes:
        enabled: true
        service-name: ${serviceName}
        namespace: ${namespace}
    rest-api:
      enabled: true
      endpoint-groups:
        HEALTH_CHECK:
          enabled: true
```

After install everything works as expected but for:

```
NAME                              CHART VERSION APP VERSION DESCRIPTION
hazelcast/hazelcast               3.5.6        4.1.1      Hazelcast IMDG is the most widely used in-memor...
```

The cluster name is created as **dev** not as **hz4MYAPP**.

mancenter:

https://mancenter-hz4.domain.com/**dev**/members

```
<hazelcast xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-4.1.xsd">
     <license-key>****</license-key>
     <cluster-name>dev</cluster-name>
     <management-center scripting-enabled="false"/>
     <security enabled="false">
          <client-block-unmapped-actions>true</client-block-unmapped-actions>
     </security>
     ...
```

mancenter:

https://mancenter-hz3.domain.com/hazelcast-mancenter/**hz3MYAPP**/members

```
<hazelcast xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.hazelcast.com/schema/config http://www.hazelcast.com/schema/config/hazelcast-config-3.12.xsd">
     <group>
          <name>MYAPP</name>
          <password>****</password>
     </group>
     <license-key>****</license-key>
     <security enabled="false">
          <client-block-unmapped-actions>true</client-block-unmapped-actions>
     </security>
     ...
```

How I can set this config al values.yaml?

This does not work.

```
yaml:
hazelcast:
...
  cluster-name: MYAPP
  instance-name: hzMYAPP
  group:
    name: hz4MYAPP
    password: 123456abcDEFG
...
```

Thanks in advance,

**Comment by jisnardo** [comment]
Hi, I've found the answer:

Question: Group Password #14082

https://github.com/hazelcast/hazelcast/issues/14082

JuKu commented on Nov 8, 2018

Why was the group password removed?
And how can i secure my hazelcast cluster now? Is there a new type of authentification / cluster password?

Improve group password configuration #11667

https://github.com/hazelcast/hazelcast/issues/11667#issuecomment-422477891

mmedenjak commented on Sep 19, 2018

Password has an unfortunate name. It was not intended to provide security, only to prevent members with different values from forming a cluster.

To this end, we already have a hazelcast property hazelcast.application.validation.token. Members with the same group name but different validation tokens will not form a cluster.

---

Management Center >>> Manage Clusters

https://docs.hazelcast.com/management-center/latest/managing-clusters.html#creating-a-cluster-configuration-using-form

Hazelcast resources

https://github.com/hazelcast/hazelcast/tree/master/hazelcast/src/main/resources

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-default.yaml

https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/resources/hazelcast-full-example.yaml

---

So, this is the sample configuration that works with the chart values.yaml.

```
hazelcast:
...
  yaml:
    hazelcast:
      cluster-name: hzMYAPP
      instance-name: hzMYAPP
...
```

```
mancenter:
...
  yaml:
    hazelcast-client:
      cluster-name: hzMYAPP
      instance-name: hzMYAPP
...
```
