### ISSUE TITLE
expose service annotations

### ISSUE THREAD

**Issue by justinrush** [hazelcast/charts#199]
Right now I have to use a post-install helm hook and wrap the chart to do this, so it would be great if this was exposed by default as seems to be the norm.

two use cases:
* setting external dns name annotation
* setting IP pool annotation

typical way is something like this in the values.yaml:
```yaml
service:
  type: LoadBalancer
  annotations: {}
```

and then the person deploying can decide to annotate or not.
