### ISSUE TITLE
Error when using the helm chart in terragrunt module helm_release

### ISSUE THREAD

**Issue by mraslam** [hazelcast/charts#221]
Error: YAML parse error on hazelcast/templates/tests/.terragrunt-source-manifest: error converting YAML to JSON: yaml: invalid leading UTF-8 octet

**Comment by hasancelik** [comment]
Hi @mraslam,

Could you provide more informations about your setup and deployment steps?

**Comment by joscabmar** [comment]
Can you check if you are escaping the config properly for your values? I had to do the following with the config:
```
hazelcast:
  yaml:
    hazelcast:
      network:
        join:
          kubernetes:
            enabled: true
            service-name: $$${serviceName}
            namespace: $$${namespace}
        rest-api:
          enabled: true
      jet:
        enabled: $$${hz.jet.enabled}
```
Please, notice the escaping syntax.
