### ISSUE TITLE
JAVA_OPTS is not reflecting the value from `hazelcast.javaOpts`

### ISSUE THREAD

**Issue by jcgarciam-signavio** [hazelcast/charts#241]
I am using this Helm Chart as a dependency to my application via the `requirements.yaml` as:
```
- name: hazelcast
    version: 3.8.0
    repository: https://hazelcast-charts.s3.amazonaws.com/
```

In my default **values.yaml** I have  the following:
```
hazelcast:
  javaOpts: foo
  image:
    pullSecrets: [docker-secret]
  annotations:
    sidecar.istio.io/inject: "true"
  yaml:

  mancenter:
    enabled: false
  metrics:
    enabled: true
  cluster:
    memberCount: 3
  resources:
    limits:
      memory: 5Gi
```
And I am testing the template via cli with:
`helm template ./ -f values.yaml`

But the resulted template is not showing the **foo** value but just the following:

```    - name: JAVA_OPTS
          value: "-Dhazelcast.config=/data/hazelcast/hazelcast.yaml -DserviceName=RELEASE-NAME-hazelcast -Dnamespace=testns -Dhazelcast.shutdownhook.policy=GRACEFUL -Dhazelcast.shutdownhook.enabled=true -Dhazelcast.graceful.shutdown.max.wait=600  -Dhazelcast.jmx=true "
```

Can you please advice why is not working?, I would like to connect with VisualVM to my Hazelcast instances to debug some memory problem, but I am unable to do it because I cannot customize the JAVA_OPTS environment variable
