### ISSUE TITLE
Issue with installation via FluxCD

### ISSUE THREAD

**Issue by KosShutenko** [hazelcast/charts#278]
I can install hazelcast via _helm install_ command, but cannot via FluxCD.
When I am trying to install hazelcast via HelmRelease in FluxCD I am getting the following error:
```
Normal  error   37s (x7 over 38s)  helm-controller  Helm upgrade failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
  line 83: mapping key "securityContext" already defined at line 33
```
I have the following  HelmRelease:
```
--- 
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: hazelcast
  namespace: hazelcast
spec: 
  chart: 
    spec: 
      chart: hazelcast
      interval: 5m
      sourceRef: 
        kind: HelmRepository
        name: hazelcast
        namespace: flux-system
  interval: 5m
  values: 
    cluster: 
      memberCount: 2
    hazelcast: 
      enabled: true
    mancenter: 
      enabled: true
      service: 
        type: ClusterIP
      ingress: 
        enabled: true
        annotations: 
          cert-manager.io/cluster-issuer: letsencrypt-prod
          kubernetes.io/ingress.class: nginx
          nginx.ingress.kubernetes.io/rewrite-target: /
        hosts: 
          - hazelcast-mancenter.pp-misc.ls-g.net
        tls: 
          - 
            hosts: 
              - hazelcast-mancenter.pp-misc.ls-g.net
            secretName: tls-secret-hazelcast-mancenter-pp-misc-ls-g-net
```
If I set `securityContext.enabled: false` installation will be completed but mancenter cannot be running because of error with mounting `/data` folder:
```
Exception in thread "main" java.lang.Error: /data can not be created. Either make it writable, or set "hazelcast.mc.home" system property to a writable directory and restart.
```

Issue in `mancenter-statefulset.yaml` file. You have part with two  `securityContext` sections:
```
       {{- if .Values.securityContext.enabled }}
        securityContext:
          runAsNonRoot: {{ if eq (int .Values.securityContext.runAsUser) 0 }}false{{ else }}true{{ end }}
          runAsUser: {{ .Values.securityContext.runAsUser }}
          runAsGroup: {{ .Values.securityContext.runAsGroup }}
          privileged: false
          readOnlyRootFilesystem: false
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
        {{- end }}
      {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
      {{- end }}
```

P.S. I found another Issue with such problem where explained why id doesn't work in FluxCD - https://github.com/fluxcd/helm-controller/issues/283#issuecomment-867693048

**Comment by martonsz** [comment]
I'm having the same issue when trying to build with Kustomize.


The following doesn't work:


```yaml
# kustomization.yaml
helmCharts:
- name: hazelcast
  version: "5.4.0"
  repo: https://hazelcast-charts.s3.amazonaws.com
  releaseName: hazelcast
```

```shell
$> kustomize build --enable-helm .
Error: map[string]interface {}(nil): yaml: unmarshal errors:
  line 85: mapping key "securityContext" already defined at line 35
```



If I set `securityContext.enabled: false` it works:

```yaml
# kustomization.yaml
helmCharts:
- name: hazelcast
  version: "5.4.0"
  repo: https://hazelcast-charts.s3.amazonaws.com
  releaseName: hazelcast
  valuesInline:
    securityContext:
      enabled: false
```

```yaml
$> kustomize build --enable-helm .
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: hazelcast
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: hazelcast
...
```

## Versions

Chart version: 5.4.0
Kustomize: {Version:kustomize/v4.5.4 GitCommit:cf3a452ddd6f83945d39d582243b8592ec627ae3 BuildDate:2022-03-28T23:12:45Z GoOs:linux GoArch:amd64}
Helm: version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
