### ISSUE TITLE
How to set class-cache-mode OFF in user-code-deployment

### ISSUE THREAD

**Issue by hudi1** [hazelcast/charts#282]
When I try:

  yaml:
    hazelcast:
      ...
      user-code-deployment:
        enabled: true
        class-cache-mode: OFF
        provider-mode: LOCAL_AND_CACHED_CLASSES

I got exception:

false is not a valid enum value

with value ETERNAL it works. I think there is bug which convert OFF value to boolean

**Comment by SemihBKGR** [comment]
Hi @hudi1 

When you declare class-cache-mode property without quote character like this:

```yaml
...
  class-cache-mode: OFF
```

It causes that the type of this value is interpreted as boolean, but it is assumed to be in string type. So, you must wrap 'OFF' by quote characters to define the value in string type.

Your configuration should be like this:

```yaml
hazelcast:
  ...
  yaml:
    hazelcast:
      user-code-deployment:
        enabled: true
        class-cache-mode: 'OFF'
        provider-mode: LOCAL_AND_CACHED_CLASSES
```
