### ISSUE TITLE
Port name in hazelcast Service must be configurable or renamed so it's compliant with Istio naming standards

### ISSUE THREAD

**Issue by JesperBerggren** [hazelcast/charts#305]
Hello,

We're using Hazelcast in a very restrictive on-premise Kubernetes cluster with Istio on top.
It's set up with DNS discovery.

In order to get it properly up and running with Istio, it's necessary to have the port renamed according to Istio naming standards.
That means it must be named <protocol>-<name>. In this case tcp-hzport.

It's currently configured like this:

_helm upgrade --install --namespace hazelcast --version 5.4.9 -f hazelcast-values.yaml hazelcast hazelcast/hazelcast --dry-run_

```
...
---
# Source: hazelcast/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    networking.istio.io/exportTo: '*'
  name: hazelcast
  labels:
    app.kubernetes.io/name: hazelcast
    helm.sh/chart: hazelcast-5.4.9
    app.kubernetes.io/instance: "hazelcast"
    app.kubernetes.io/managed-by: "Helm"
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: hazelcast
    app.kubernetes.io/instance: "hazelcast"
    role: hazelcast
  ports:
  - protocol: TCP
    port: 5701
    targetPort: hazelcast
    name: hzport
---
...
```

Preferably it should be possible to rename the port in the values file. If not, then it should be renamed to tcp-hzport.

Thanks!

Best regards
Jesper Berggren
