### ISSUE TITLE
Permit enablement of CP subsystem in hazelcast.yaml for hazelcast chart

### ISSUE THREAD

**Issue by gbarnett-hz** [hazelcast/charts#379]
There's no quick and simple way to enable the CP subsystem when using the `hazelcast` chart.

Default is disabled; but there should be a one-liner to enable this so users can experiment with CP features.

**Comment by semihbkgr** [comment]
Hi @gbarnett-hz 

Configuring `hazelcast.yaml.hazelcast.cp-subsystem` field in the values yaml file will actually enable cp subsystem.

e.g.
```yaml
cluster:
  memberCount: 5
hazelcast:
  yaml:
    hazelcast:
      cp-subsystem:
        cp-member-count: 5
        group-size: 3
        session-time-to-live-seconds: 300
        session-heartbeat-interval-seconds: 5
        missing-cp-member-auto-removal-seconds: 14400
        fail-on-indeterminate-operation-state: false
```

```shell
$ helm install hz hazelcast/hazelcast --values=values.yaml
```

Checking the logs one of the member:

```
2023-08-22 16:23:12,312 [ INFO] [main] [c.h.c.CPSubsystem]: [172.17.0.6]:5701 [dev] [5.3.1] CP Subsystem is enabled with 5 members.
```

Basically, the fields 'hazelcast.yaml' is used to configure hazelcast cluster members.
