### ISSUE TITLE
[HelmChart] Feature Request: Make path configurable in mancenter.ingress block

### ISSUE THREAD

**Issue by m4dm4rtig4n** [hazelcast/charts#475]
### Description

Currently, the `Ingress` template for Hazelcast Management Center (`mancenter`) uses a fixed path `/` in the `spec.rules[].http.paths[].path` field:

```yaml
- path: "/"
  pathType: Prefix
  backend:
    service:
      name: {{ $serviceName }}
      port:
        name: http
```

This hardcoded value prevents users from exposing the UI under a custom path like `/hazelcast`, which is often required in environments using reverse proxies or ingress path-based routing (e.g., APISIX, Traefik, NGINX).

---

### Proposed Enhancement

Introduce a new optional value in `values.yaml`:

```yaml
mancenter:
  ingress:
    path: "/"
```

And update the `Ingress` template:

```yaml
- path: {{ .Values.mancenter.ingress.path | default "/" | quote }}
  pathType: Prefix
  backend:
    service:
      name: {{ $serviceName }}
      port:
        name: http
```

---

### Benefits

* Enables path-based routing flexibility
* Remains backward compatible (default path remains `/`)
* Unblocks users in environments where base paths are used

---

### Use Case Example

With this enhancement, users could define:

```yaml
mancenter:
  ingress:
    enabled: true
    hosts:
      - my.domain.local
    path: "/hazelcast"
```

And access Management Center via `https://my.domain.local/hazelcast`.

---

Thank you for considering this feature!
